# Generated by Django 3.1 on 2022-12-07 21:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Competition',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('description', models.TextField(verbose_name='Description')),
                ('cover_img', models.FileField(blank=True, upload_to='uploading/competition/', verbose_name='Cover Image')),
                ('end_date', models.DateTimeField(blank=True, verbose_name='End Date')),
                ('evaluation_func', models.TextField(blank=True, verbose_name='Evaluation Function')),
                ('labels', models.TextField(blank=True, verbose_name='Labels')),
                ('download_link', models.CharField(blank=True, max_length=150, verbose_name='Download Link')),
            ],
        ),
        migrations.CreateModel(
            name='UploadingFile',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('file', models.FileField(blank=True, upload_to='uploading/%Y/%m/%d/', verbose_name='File')),
                ('uploading_time', models.DateTimeField(auto_now_add=True, verbose_name='Uploading Time')),
                ('allowed_groups', models.ManyToManyField(blank=True, to='auth.Group')),
                ('allowed_users', models.ManyToManyField(blank=True, related_name='allowed_files', to=settings.AUTH_USER_MODEL)),
                ('uploader', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_files', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'File',
                'verbose_name_plural': 'Files',
            },
        ),
        migrations.CreateModel(
            name='CompetitionSubmission',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('content', models.TextField(verbose_name='Content')),
                ('score', models.CharField(max_length=100, verbose_name='Score')),
                ('submit_time', models.DateTimeField(auto_now_add=True, verbose_name='Submit Time')),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auxiliary.competition', verbose_name='Competition')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Submitter')),
            ],
        ),
    ]
