# Generated by Django 3.1 on 2023-06-22 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auxiliary', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='competitionsubmission',
            name='submit_file',
            field=models.FileField(blank=True, default=None, null=True, upload_to='competition/submissions/%Y/%m/%d/', verbose_name='Submit File'),
        ),
        migrations.AlterField(
            model_name='competition',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='End Date'),
        ),
        migrations.AlterField(
            model_name='competitionsubmission',
            name='content',
            field=models.TextField(blank=True, default=None, null=True, verbose_name='Content'),
        ),
    ]
